version: '3.3'
services:
    restservice:
        build:
            context: .
            dockerfile: restservice.dockerfile
        ports:
          - "8082:8082"
        networks:
          - isolated_nw2
        volumes:
          - /tmp
        container_name: restserviceCommande
        depends_on:
          - pgdb

    pgdb:
        image: postgres
        ports:
          - "5432:5432"
        networks:
          - isolated_nw2
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: riovas
        container_name: postgresCommande

networks:
    isolated_nw2:
        driver: bridge